import React from 'react'

export default function Collection() {
  return (
    <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit odio quidem maiores fuga delectus quae debitis repellendus accusamus adipisci magnam ab, perspiciatis omnis voluptate aspernatur labore ipsum ullam sit quis.
    Modi iusto esse aliquid? Nemo magni, placeat facilis, exercitationem culpa numquam aspernatur aut velit sequi nihil consectetur amet sed quod praesentium laudantium neque doloremque? Asperiores repellendus magni et harum quod?
    Harum eum eius aut illum rem et, unde accusamus quasi eligendi delectus quo voluptatibus ad placeat reprehenderit, itaque repellendus mollitia? Totam animi cumque consequatur repellendus nihil? Repellendus consequatur reiciendis accusamus.
    Asperiores, rerum. Itaque, sint sapiente fugiat omnis aliquam unde enim autem totam, quas maiores aliquid blanditiis laudantium esse vero ut ducimus labore fugit dicta quasi tempore. Corrupti repellendus unde eum?
    Dicta, error recusandae modi repudiandae debitis quod inventore perspiciatis rerum reprehenderit repellat. Repellendus aut architecto debitis sint. Tempore ratione officiis, ea, architecto dolores soluta, laborum ex nostrum hic corporis ipsum.
    Maxime animi soluta debitis molestiae itaque optio excepturi minima provident fuga ex inventore aliquid deleniti recusandae, distinctio, vitae ut rem assumenda facilis. Itaque eius blanditiis cupiditate in molestiae iste placeat.
    Dolor ipsum veniam iure sint incidunt non obcaecati voluptas doloremque, minus facere voluptates dignissimos pariatur dolores, repellat maiores? Soluta fugiat molestias nulla iure facere recusandae velit id. Delectus, expedita quo.
    Assumenda facere nobis et nostrum dolores quis necessitatibus ipsa quam similique id reiciendis, officia incidunt soluta rerum voluptas pariatur, at ex atque est possimus tempore. Quas recusandae architecto vero quo.
    Pariatur eius voluptates modi impedit vero maxime, deserunt ducimus numquam fuga sapiente repudiandae cum explicabo quas distinctio fugiat iusto, excepturi ratione perspiciatis. Blanditiis fugit amet eos sit esse sunt in!
    Ullam corporis doloremque hic ratione dolorem autem atque ab repudiandae, at iure numquam rem aspernatur tempore fuga, similique sed facere ad aut sint magnam! Odit, provident! Aperiam illo blanditiis dicta?
    Qui rem optio blanditiis repudiandae error vitae omnis maiores quibusdam sapiente veniam laborum, quisquam culpa possimus cumque amet suscipit ratione ex quasi magni nulla nihil deserunt asperiores earum. Et, eaque.
    Architecto saepe quisquam earum minus, perspiciatis reiciendis, est praesentium dolore, similique odio excepturi id maxime. Nobis quos, repellendus vitae veniam assumenda aspernatur! Modi quos nostrum possimus laudantium, ipsum dolore sit.
    Numquam quae rerum sint, officia doloremque nemo nesciunt repellendus laboriosam! Impedit sed repudiandae fugit. Quo laudantium quas nostrum eligendi magnam eveniet tempora impedit eos mollitia, illum esse aliquam aliquid quibusdam.
    Consectetur praesentium obcaecati quasi blanditiis illo doloribus cumque ut corporis ullam saepe optio aliquid, cum eligendi vitae repellat, vero voluptatum sunt. Molestiae perspiciatis corporis dicta. Nihil atque sequi dolorem. Reiciendis.
    Rem veniam officia quo sequi neque repudiandae mollitia illum nemo quas laborum, cumque pariatur id architecto tenetur molestiae commodi delectus eveniet consequatur. Repellendus eum sint dicta voluptate doloremque doloribus suscipit.
    Ipsa, possimus ipsum perspiciatis distinctio adipisci dolorum mollitia sit temporibus dolores deserunt, dignissimos non! Sunt dolore quis omnis voluptatum eaque quibusdam cupiditate, libero aut corrupti fuga neque deserunt perspiciatis sed.
    Vel in, repudiandae, mollitia magni aspernatur aliquam veniam placeat recusandae alias maxime possimus iure cupiditate error? Aliquam omnis esse ex natus modi optio soluta placeat reprehenderit est, maiores nulla nobis!
    Atque cupiditate corrupti nisi qui natus voluptatum aliquam, velit ut, animi accusantium tempora, earum ratione vel aliquid mollitia delectus. Perferendis, nobis labore minima similique dolores voluptatibus ipsa sint qui atque!
    Molestiae minima corrupti repellat fugit tempora earum voluptatum sunt explicabo eius nam enim eos nobis beatae placeat ad autem natus quas, nulla veritatis non accusamus deserunt amet. Consequuntur, repellat tenetur.
    Eligendi cupiditate odit aliquid modi nisi deserunt veniam alias aliquam cum animi magnam, amet eius voluptates dicta quas unde, vel consequuntur explicabo? Consequatur architecto sequi distinctio quaerat magnam eos nihil.
    Maxime ab reiciendis quibusdam ullam ipsum qui officiis molestias cum quae doloribus iure tempora debitis corrupti, rerum distinctio commodi nihil blanditiis nostrum. Neque nobis cum laboriosam natus voluptatem autem veniam.
    Quos dolorum perspiciatis pariatur amet molestiae. Quidem atque quis voluptates? A cum quibusdam aspernatur nobis laudantium, error similique architecto voluptatem quae ipsum fugit incidunt ipsa. Repellendus, laborum? Sequi, praesentium delectus!
    Corrupti rerum quidem, molestiae pariatur quia tenetur amet fuga rem dolore! Dolor autem, debitis ipsum hic libero nesciunt doloremque sed inventore cum, quaerat quod corrupti eius fuga consequuntur, et quo.
    Eligendi tempora quaerat illum adipisci reprehenderit odio commodi fugiat praesentium perferendis, odit voluptatem nobis ipsum, ad placeat illo deserunt repellat nulla voluptate? Saepe quaerat cupiditate illum inventore explicabo eveniet aperiam!
    Vel ipsa nemo maiores debitis facilis laboriosam officiis ipsam corrupti illum quo optio voluptas, in esse voluptate quibusdam consequuntur culpa. Facere, modi. Qui, nihil assumenda officiis mollitia autem quasi optio!
    Incidunt, maiores eius, quas cupiditate id esse modi corrupti porro nesciunt, sunt molestiae corporis pariatur ad ipsa culpa doloribus quibusdam perferendis. Cupiditate vitae quo ea, incidunt esse suscipit alias quasi!
    Adipisci nam quas, similique libero maxime, ab magnam praesentium animi perspiciatis nihil officia. Voluptates consequuntur, quas iste exercitationem voluptatibus consectetur reiciendis, enim esse doloremque odit optio quidem atque voluptate hic!
    Error ex amet in. Ab, ratione quisquam distinctio doloribus architecto consequuntur voluptatibus quia magnam omnis, animi illum, praesentium cumque vel dolores eum est quas fugiat? Ipsum, error. Totam, in libero?
    Eligendi voluptate fuga illum error et odit deleniti, repellat provident harum iste nisi, cum doloribus ullam velit, repellendus eveniet? Est facilis voluptas veritatis non explicabo quas error, ipsum optio commodi!
    In cupiditate quod nisi, nam inventore quisquam est eaque ut eius dolorum iure veniam, repudiandae laborum voluptatum ipsam enim aliquid modi molestias. Facere et ullam modi cumque cupiditate voluptate vitae.
    Dolorum reiciendis beatae unde, consequatur cumque, suscipit deserunt esse voluptates, quo illum vero officia natus! Eveniet, illo velit illum libero reprehenderit nihil? Autem dolore, provident fuga explicabo in ullam temporibus!
    Necessitatibus animi, nisi voluptates dolores ducimus quibusdam nulla minus cumque suscipit accusamus neque nobis, quaerat repellendus delectus praesentium vero hic, doloremque esse iste reiciendis officia ab dolorum. Eum, nobis consequatur!
    Omnis minus quis cum assumenda non quaerat suscipit unde animi voluptatum architecto voluptatibus maxime, quasi, consectetur eaque ratione dolorem quibusdam consequatur! Eaque ducimus facere impedit dolorem magnam enim vel non!
    Nulla libero quis cumque laudantium voluptatum nihil placeat eaque? Ipsam ullam laudantium, excepturi in ad ipsum quod quae odit provident porro voluptatibus perspiciatis aperiam, veritatis culpa, ut officiis enim doloremque?
    Animi quas dolore nihil rem quisquam harum libero voluptas eos mollitia, sequi facere voluptatem consequuntur illo iusto eveniet sapiente excepturi hic corrupti tenetur ullam alias ut ratione ex? Ducimus, provident?
    Necessitatibus eaque eius quaerat earum, iure deserunt animi natus est provident laborum iste sequi qui! Libero praesentium sapiente temporibus fugit magnam, accusantium laborum consectetur cupiditate exercitationem. Iste optio odio esse?
    In amet consectetur quisquam nisi dolore, dolorum harum optio pariatur iusto ducimus maiores, quidem modi cum quis inventore praesentium perspiciatis enim adipisci fuga! Ipsa explicabo reiciendis excepturi quae quos voluptate.
    Deserunt ipsum, quod excepturi debitis voluptatum nobis soluta corporis maiores atque nisi facilis iusto. Perspiciatis odio magni soluta incidunt eos sit quisquam! Atque doloribus explicabo itaque minima iusto quod ex.
    Sit expedita at in voluptate harum numquam soluta placeat id accusamus architecto? Totam repudiandae impedit aliquam a architecto veniam quod harum, corrupti quisquam. Voluptate ut eveniet suscipit accusamus, dolores aliquid!
    Quo ratione ipsam est. Aut in at eveniet voluptate atque velit vitae molestiae est ducimus officia ad nihil, cum accusantium quidem ipsa excepturi, molestias accusamus praesentium exercitationem. Atque, quidem eligendi.
    Maiores praesentium iusto modi neque eos sint laboriosam deleniti porro, ducimus quas illo repellat nulla cumque soluta cum consequuntur sapiente incidunt quia odio vitae, molestias impedit! Sapiente fugit amet voluptas.
    Iusto voluptates iure voluptatibus doloremque, architecto error dolorum tenetur nam. Quos sequi quam, ipsum dolore eos, sunt porro eligendi accusantium labore eveniet nemo in optio. Expedita ducimus explicabo non ut.
    Consectetur, commodi corporis facilis repellat ipsam et quo! Ducimus sunt exercitationem, eaque magni, distinctio vero voluptatem cumque quam repellat tempora provident! Sint eveniet ratione iste, quisquam doloremque eligendi! Quia, illum?
    Voluptate officiis accusamus illo repudiandae in laudantium nobis ipsa placeat culpa labore tempora nam animi magnam et, iste incidunt eius eos quos quaerat nesciunt cumque quae. Aliquid similique architecto ab.
    Sit adipisci maxime delectus eius omnis libero exercitationem fugiat quibusdam expedita saepe eum aliquid, voluptatem odit eligendi repellat aut deleniti fugit non dolores consequuntur labore eveniet. Aspernatur veniam dolores veritatis.
    Qui blanditiis, doloribus illum error unde id sunt. Labore, optio nesciunt! Velit quisquam obcaecati dignissimos nihil, quia voluptatem placeat tenetur ducimus optio, ipsa eligendi veritatis rerum quos odit, accusamus quasi!
    Distinctio, expedita rerum. Asperiores libero ex numquam reiciendis assumenda eaque aspernatur cupiditate atque consequatur perferendis enim, voluptate quasi fugiat praesentium deleniti voluptatibus quaerat reprehenderit accusantium architecto sapiente aliquid tenetur. Repudiandae?
    Similique perferendis aliquam incidunt cupiditate laborum quisquam error atque corporis, nostrum molestias. Quia harum distinctio asperiores. Impedit possimus neque earum dicta non tempore officia mollitia quae nesciunt, molestiae cum ipsa!
    Non iste libero blanditiis, saepe quod accusantium perferendis error ipsam velit consequuntur eveniet fugit corporis reiciendis nisi enim vel, ad minima atque totam delectus. Reprehenderit alias error vitae voluptate aliquam!
    Sequi illo dolorum voluptatem facilis ab fugit libero harum odio doloremque, perferendis dignissimos? Voluptatibus neque animi, perferendis dolore quaerat, cum modi voluptas numquam vel reiciendis quis, aspernatur totam nostrum nesciunt?
    Sit ab eius ipsa fugiat culpa enim architecto incidunt, ipsam, necessitatibus, eaque suscipit tempore repudiandae? Libero sapiente cupiditate provident perferendis dolorem, magni minus dolores dignissimos repellendus animi nobis quidem impedit.
    Esse earum dicta autem suscipit pariatur. Sapiente voluptatibus hic ab atque non quibusdam, alias aliquid nihil ad eligendi earum sunt perferendis quod repudiandae deleniti excepturi. Dolore soluta delectus aliquam laudantium!
    Deleniti assumenda est dolore, ad ex ea culpa alias hic impedit eligendi repellat id omnis veritatis temporibus tempora placeat accusamus repellendus earum labore. Voluptatum a vel eos commodi aperiam nesciunt?
    Facilis autem magni ad minus similique eius quis cupiditate dignissimos iure amet. Quidem optio a, laboriosam, facilis numquam alias quo doloremque eligendi quae nostrum, voluptate quas modi doloribus velit ipsum.
    Dolores magnam minus eius, dolorum in alias, maiores ducimus dolore commodi magni quam non culpa dignissimos pariatur, voluptas atque ullam asperiores. Aut facere officiis amet consequuntur recusandae nobis, perspiciatis dolorem!
    Explicabo voluptate veniam minima aliquam ab earum fugit quos optio quas dicta dolor incidunt, quibusdam aliquid praesentium. Quia, id officia totam veritatis, doloribus vitae repellendus velit ullam, neque perferendis deleniti!
    Distinctio, nulla officia nobis consectetur perspiciatis, vel nihil voluptatem sed ducimus vitae reiciendis veritatis, quidem necessitatibus possimus? Natus dolorem ipsum nihil! Eum beatae, officia assumenda cumque ea accusamus excepturi pariatur?
    Exercitationem molestiae at in eveniet libero obcaecati id. Aliquam veniam, iste fugiat exercitationem laboriosam id omnis vero. Amet exercitationem modi a, placeat animi quaerat fugiat tempora odit, laudantium, qui possimus.
    Perferendis nisi soluta, pariatur tenetur fugit ducimus dolore eius impedit asperiores explicabo officia eligendi distinctio mollitia vel, et cum autem quisquam alias qui! Mollitia illo veniam corrupti ex optio molestias.
    Maiores in, expedita deleniti earum quisquam error similique blanditiis officiis ut dolores nemo accusamus ad incidunt aut non neque perspiciatis magnam et laborum quam! Expedita perferendis vel exercitationem architecto minus.</div>
  )
}
